# Generated by Django 4.0 on 2022-01-08 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('brand', models.CharField(max_length=64, null=True)),
                ('category', models.CharField(max_length=64, null=True)),
                ('description', models.TextField(blank=True, max_length=256, null=True)),
                ('rating', models.DecimalField(decimal_places=3, max_digits=4)),
                ('num_reviews', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=3, max_digits=7)),
                ('count_in_stock', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
