# Generated by Django 4.0 on 2022-01-20 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_review_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
