# Generated by Django 4.0 on 2022-01-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_review_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
    ]
